service: aws-node-express-api-project
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: '20201221'  

functions:
  api:
    handler: dist/handler.handler
    events:
      - http:
          path: '{proxy+}' # Catch-all route to forward all requests to the Express app
          method: any
          cors: true

# Plugins for easier development and deployment
plugins:
  - serverless-dotenv-plugin # For environment variable management

custom:
  cors:
    origin: '*' # Replace with specific domains for production

package: 
  include:
    - .env

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: image-processing3244f # Unique bucket name
